# Generated by Django 5.2.7 on 2025-10-12 11:52

import autoslug.fields
import django.db.models.deletion
import django.utils.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_userprofile_username_alter_userprofile_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='-', max_length=256),
        ),
        migrations.CreateModel(
            name='InFlowAIProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='-', max_length=200)),
                ('assistant_prompt', models.TextField(default='-')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_link', autoslug.fields.AutoSlugField(editable=False, populate_from='project_name', slugify=django.utils.text.slugify, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
