# Generated by Django 5.2.7 on 2025-10-18 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_userprofile_email_inflowaiproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inflowaiproject',
            old_name='company_link',
            new_name='project_link',
        ),
    ]
